name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Make Dotenv
      run: |
        touch .env
        echo VITE_SUPABASE_PROJECT_ID=${{ vars.VITE_SUPABASE_PROJECT_ID }} >> .env
        echo VITE_SUPABASE_ANON_KEY=${{ vars.VITE_SUPABASE_ANON_KEY }} >> .env
        echo VITE_SUPABASE_HENRY_IDL=${{ vars.VITE_SUPABASE_HENRY_ID }} >> .env

    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm run build

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: build/app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}